GET http://localhost:3000/api/data-access/test?pageIndex=2&pageSize=3


GET http://localhost:3000/api/data-access/member/info


GET http://localhost:3000/api/data-access/member/schema


GET http://localhost:3000/api/status


POST http://localhost:3000/api/data-access/tables/customer_notes
Content-Type: application/json

[
  {
    "name": "note",
    "type": "text",
    "nullable": false
  },
  {
    "name": "created_at",
    "type": "timestamp",
    "nullable": false
  }
]
